# Populates services/api/.env from `terraform output`.
# Overwrites the file. Sensitive outputs (App Insights connection string)
# are read with `-raw` and never printed to the console.
$ErrorActionPreference = "Stop"

$repoRoot = Split-Path -Parent $PSScriptRoot
$infra    = Join-Path $repoRoot "infra"
$envPath  = Join-Path $repoRoot "services\api\.env"

if (-not (Test-Path (Join-Path $infra "terraform.tfstate"))) {
    Write-Host "No terraform.tfstate found in $infra. Run 'terraform apply' first." -ForegroundColor Red
    exit 1
}

Push-Location $infra
try {
    $projectEndpoint = terraform output -raw foundry_project_endpoint
    $deployment      = terraform output -raw model_deployment_name
    $appInsights     = terraform output -raw application_insights_connection_string
} catch {
    Pop-Location
    Write-Host "Failed to read Terraform outputs. Ensure 'terraform apply' completed successfully." -ForegroundColor Red
    exit 1
}
Pop-Location

$content = @"
# Generated by scripts/populate-env.ps1 from terraform output.
# Regenerate after every `terraform apply` if outputs change.
AZURE_AI_FOUNDRY_PROJECT_ENDPOINT=$projectEndpoint
FOUNDRY_MODEL_DEPLOYMENT_ANALYST=$deployment
FOUNDRY_MODEL_DEPLOYMENT_RECOMMENDER=$deployment
FOUNDRY_MODEL_DEPLOYMENT_VALIDATOR=$deployment
AZURE_AI_FOUNDRY_AUTH_MODE=entra
APPLICATIONINSIGHTS_CONNECTION_STRING=$appInsights
DEMO_RESET_ENABLED=false
"@

$content | Set-Content -Path $envPath -Encoding utf8 -NoNewline
Write-Host "Wrote $envPath" -ForegroundColor Green
Write-Host "  Project endpoint   : $projectEndpoint"
Write-Host "  Model deployment   : $deployment"
Write-Host "  App Insights conn  : (hidden)"
Write-Host ""
Write-Host "Next: run 'python scripts/sync_foundry_agents.py --apply' to create/update the remote agents."
