# Populates services/api/.env from `terraform output`.
# Overwrites the file. Sensitive outputs (App Insights connection string)
# are read with `-raw` and never printed to the console.
$ErrorActionPreference = "Stop"

$repoRoot = Split-Path -Parent $PSScriptRoot
$infra    = Join-Path $repoRoot "infra"
$envPath  = Join-Path $repoRoot "services\api\.env"

if (-not (Test-Path (Join-Path $infra "terraform.tfstate"))) {
    Write-Host "No terraform.tfstate found in $infra. Run 'terraform apply' first." -ForegroundColor Red
    exit 1
}

Push-Location $infra
try {
    $endpoint    = terraform output -raw ai_services_endpoint
    $projectName = terraform output -raw foundry_project_name
    $deployment  = terraform output -raw model_deployment_name
    $appInsights = terraform output -raw application_insights_connection_string
} catch {
    Pop-Location
    Write-Host "Failed to read Terraform outputs. Ensure 'terraform apply' completed successfully." -ForegroundColor Red
    exit 1
}
Pop-Location

$content = @"
# Generated by scripts/populate-env.ps1 from terraform output.
# Regenerate after every `terraform apply` if outputs change.
AZURE_AI_FOUNDRY_ENDPOINT=$endpoint
AZURE_AI_FOUNDRY_PROJECT_NAME=$projectName
AZURE_AI_FOUNDRY_DEPLOYMENT=$deployment
AZURE_AI_FOUNDRY_API_VERSION=2024-10-21
AZURE_AI_FOUNDRY_AUTH_MODE=entra
APPLICATIONINSIGHTS_CONNECTION_STRING=$appInsights
DEMO_RESET_ENABLED=false
"@

$content | Set-Content -Path $envPath -Encoding utf8 -NoNewline
Write-Host "Wrote $envPath" -ForegroundColor Green
Write-Host "  Endpoint          : $endpoint"
Write-Host "  Project           : $projectName"
Write-Host "  Deployment        : $deployment"
Write-Host "  App Insights conn : (hidden)"
