# Populates services/api/.env from `terraform output`.
# Overwrites the file. Sensitive outputs (App Insights connection string)
# are read with `-raw` and never printed to the console.
$ErrorActionPreference = "Stop"

$repoRoot = Split-Path -Parent $PSScriptRoot
$infra    = Join-Path $repoRoot "infra"
$envPath  = Join-Path $repoRoot "services\api\.env"

if (-not (Test-Path (Join-Path $infra "terraform.tfstate"))) {
    Write-Host "No terraform.tfstate found in $infra. Run 'terraform apply' first." -ForegroundColor Red
    exit 1
}

Push-Location $infra
try {
    $projectEndpoint = terraform output -raw foundry_project_endpoint
    $deployment      = terraform output -raw model_deployment_name
    $appInsights     = terraform output -raw application_insights_connection_string
    # Optional: these are empty when the matching feature is disabled.
    $router          = terraform output -raw router_deployment_name 2>$null
    $judge           = terraform output -raw judge_deployment_name 2>$null
    $searchEndpoint  = terraform output -raw search_endpoint 2>$null
    $knowledgeStore  = terraform output -raw knowledge_storage_account_name 2>$null
    $knowledgeBlob   = terraform output -raw knowledge_container_name 2>$null
} catch {
    Pop-Location
    Write-Host "Failed to read Terraform outputs. Ensure 'terraform apply' completed successfully." -ForegroundColor Red
    exit 1
}
Pop-Location

# Regenerating must not silently wipe the learner's suffix; publishing
# refuses to run without it.
$suffix = ""
if (Test-Path $envPath) {
    $existing = Select-String -Path $envPath -Pattern '^WORKSHOP_LEARNER_SUFFIX=(.*)$' | Select-Object -First 1
    if ($existing) { $suffix = $existing.Matches[0].Groups[1].Value }
}

$content = @"
# Generated by scripts/populate-env.ps1 from terraform output.
# Regenerate after every 'terraform apply' if outputs change.
AZURE_AI_FOUNDRY_PROJECT_ENDPOINT=$projectEndpoint
FOUNDRY_MODEL_DEPLOYMENT_ANALYST=$deployment
FOUNDRY_MODEL_DEPLOYMENT_RECOMMENDER=$deployment
FOUNDRY_MODEL_DEPLOYMENT_VALIDATOR=$deployment
FOUNDRY_MODEL_DEPLOYMENT_EXPLAINER=$deployment

# Module 7 (router) and Module 9 (evaluation judge).
FOUNDRY_MODEL_DEPLOYMENT_ROUTER=$router
FOUNDRY_MODEL_DEPLOYMENT_JUDGE=$judge

# Module 6 (Foundry IQ knowledge plane).
AZURE_SEARCH_ENDPOINT=$searchEndpoint
KNOWLEDGE_STORAGE_ACCOUNT=$knowledgeStore
KNOWLEDGE_CONTAINER=$knowledgeBlob

# Required before publishing agents. Lowercase a-z, 0-9 or '-', max 24 chars.
WORKSHOP_LEARNER_SUFFIX=$suffix

AZURE_AI_FOUNDRY_AUTH_MODE=entra
APPLICATIONINSIGHTS_CONNECTION_STRING=$appInsights
DEMO_RESET_ENABLED=false

# API_SHARED_KEY is deliberately unset. Locally the Vite dev server proxies
# /api to this uvicorn, so nothing sits in front to attach a key. The API only
# insists on one when it detects App Service, where it is reachable from the
# internet.
"@

$content | Set-Content -Path $envPath -Encoding utf8
Write-Host "Wrote $envPath" -ForegroundColor Green
Write-Host "  Project endpoint   : (written to .env)"
Write-Host "  Model deployment   : $deployment"
Write-Host "  Router / judge     : $router / $judge"
Write-Host "  App Insights conn  : (hidden)"
if (-not $suffix) {
    Write-Host "  Learner suffix     : NOT SET - publishing will refuse to run" -ForegroundColor Yellow
}
Write-Host ""
Write-Host "Next:"
Write-Host "  1. Set WORKSHOP_LEARNER_SUFFIX in services\api\.env"
Write-Host "  2. python scripts/validate_agent_definitions.py"
Write-Host "  3. python scripts/publish_prompt_agents.py --suffix <your-alias> --apply"
