"""Turn validated agent outputs into the API response object."""

from __future__ import annotations

from ..agents.shared.contracts import (
    Citation,
    DataAnalystOutput,
    ResourceRef,
    SupportRecommendationDraft,
    ValidatorReport,
)
from ..human_review import HumanReviewState
from ..models import Recommendation, RecommendationCitation, RecommendationResource


def _to_recommendation_citation(citation: Citation) -> RecommendationCitation:
    return RecommendationCitation(
        citation_id=citation.citation_id,
        dealer_group_id=citation.dealer_group_id,
        source_type=citation.source_type.value,
        source_title=citation.source_title,
        section_or_page=citation.section_or_page,
        evidence_summary=citation.evidence_summary,
        source_ref=citation.source_ref,
        retrieved_at=citation.retrieved_at,
        confidence=citation.confidence,
    )


def build_recommendation(
    *,
    analysis: DataAnalystOutput,
    draft: SupportRecommendationDraft,
    allowed: tuple[ResourceRef, ...],
    report: ValidatorReport,
    provider_display: str,
) -> Recommendation:
    """Merge the analyst's findings with the recommender's plan."""

    by_id = {r.id: r for r in allowed}
    resource_matches = [
        RecommendationResource(id=r.id, label=r.label, kind=r.kind)
        for r in (by_id[rid] for rid in draft.resource_ids if rid in by_id)
    ]
    return Recommendation(
        dealer_group_id=draft.dealer_group_id,
        detected_need=analysis.analysis.detected_need or draft.detected_need,
        evidence_summary=list(analysis.analysis.evidence_bullets),
        rationale=draft.rationale,
        support_tier=draft.support_tier,
        recommended_frequency=draft.recommended_frequency,
        grouping_guidance=draft.grouping_guidance,
        resource_matches=resource_matches,
        manager_next_steps=list(draft.manager_next_steps),
        progress_monitoring=list(draft.progress_monitoring),
        review_window_days=draft.review_window_days,
        decision_rule=draft.decision_rule,
        caveats=list(draft.caveats),
        goal_suggestions=list(draft.goal_suggestions),
        strategy_suggestions=list(draft.strategy_suggestions),
        citations=[_to_recommendation_citation(c) for c in draft.citations],
        completeness={"ok": report.passed, "missing": list(report.issue_codes)},
        human_review_state=HumanReviewState.PENDING_REVIEW.value,
        generated_by=f"Generated by three collaborating agents via {provider_display}.",
    )
